apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dpf-hcp-bridge-operator.fullname" . }}-manager-rolebinding
  labels:
    {{- include "dpf-hcp-bridge-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "dpf-hcp-bridge-operator.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "dpf-hcp-bridge-operator.serviceAccountName" . }}
  namespace: {{ include "dpf-hcp-bridge-operator.namespace" . }}
