apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "dpf-hcp-bridge-operator.namespace" . }}
  labels:
    {{- with .Values.namespaceLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- include "dpf-hcp-bridge-operator.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
