apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dpf-hcp-bridge-operator.serviceAccountName" . }}
  namespace: {{ include "dpf-hcp-bridge-operator.namespace" . }}
  labels:
    {{- include "dpf-hcp-bridge-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
