# This rule is not used by the project dpf-hcp-bridge-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to provisioning.dpu.hcp.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dpf-hcp-bridge-operator
    app.kubernetes.io/managed-by: kustomize
  name: dpfhcpbridge-viewer-role
rules:
- apiGroups:
  - provisioning.dpu.hcp.io
  resources:
  - dpfhcpbridges
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - provisioning.dpu.hcp.io
  resources:
  - dpfhcpbridges/status
  verbs:
  - get
