# This rule is not used by the project dpf-hcp-provisioner-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over provisioning.dpu.hcp.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dpf-hcp-provisioner-operator
    app.kubernetes.io/managed-by: kustomize
  name: dpfhcpprovisioner-admin-role
rules:
- apiGroups:
  - provisioning.dpu.hcp.io
  resources:
  - dpfhcpprovisioners
  verbs:
  - '*'
- apiGroups:
  - provisioning.dpu.hcp.io
  resources:
  - dpfhcpprovisioners/status
  verbs:
  - get
