apiVersion: v2
name: dpf-hcp-provisioner-operator
description: Kubernetes operator that provisions DPF and Hypershift, abstracting the complexity of Hypershift management and automating the full lifecycle of Hypershift in a DPU context
type: application
version: 0.1.0
appVersion: v0.1.0
keywords:
  - operator
  - kubernetes
  - hypershift
  - dpu
  - bluefield
  - openshift
home: https://github.com/rh-ecosystem-edge/dpf-hcp-provisioner-operator
sources:
  - https://github.com/rh-ecosystem-edge/dpf-hcp-provisioner-operator
maintainers:
  - name: Red Hat Ecosystem Edge Team
